---
- name: Converge
  hosts: all
  tasks:
    - name: "Disable guru overlay"
      include_role:
        name: "portage-overlay-cfg"
      vars:
        gentoo_overlay_repos:
          - name: guru
            state: disabled
