---
- name: Converge
  hosts: all
  tasks:
    - name: "Enable guru overlay"
      include_role:
        name: "gentoo-overlay"
      vars:
        gentoo_overlay_repos:
          - name: guru
    - name: "Disable guru overlay"
      include_role:
        name: "gentoo-overlay"
      vars:
        gentoo_overlay_repos:
          - name: guru
            state: disabled
