---

- name: Verify repo_disable
  hosts: all
  gather_facts: false
  tasks:
    # If repo is disabled - the directory should still exist
    - name: Check that guru directory exists
      include_tasks: ../resources/verify/check_directory_exists.yml

    - name: Check that guru is disabled
      lineinfile:
        name: "/etc/portage/repos.conf/eselect-repo.conf"
        line: "[guru]"
        state: absent
      check_mode: yes
      register: assertion
      failed_when: (assertion is changed) or (assertion is failed)
